AplicationWebMVC/Models/AccesoViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace AplicationWebMVC.Models
{
    public class AccesoViewModel
    {
        [Required(ErrorMessage = "El Email es obligatorio")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
        [Display(Name = "Recordar datos?")]
        public bool RememberMe { get; set; }
    }
}

AplicationWebMVC/Models/AppUsuario.cs
using Microsoft.AspNetCore.Identity;

namespace AplicationWebMVC.Models
{
    public class AppUsuario : IdentityUser
    {
        public string Nombre { get; set; }
        public string Url { get; set; }
        public Int32 CodigoPais { get; set; }
        public string Telefono { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public bool Estado { get; set; }
    }
}

AplicationWebMVC/Models/ErrorViewModel.cs
namespace AplicationWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AplicationWebMVC/Models/RegistroViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace AplicationWebMVC.Models
{
    public class RegistroViewModel
    {
        [Required(ErrorMessage = "El Email es obligatorio")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
        
        [Required(ErrorMessage = "La confirmarcion de contraseña es obligatoria")]
        [Compare("Password",ErrorMessage ="La contraseña y la confirmacion de contraseña no coinciden")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar Contraseña")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }
        public string Url { get; set; }
        public Int32 CodigoPais { get; set; }
        public string Telefono { get; set; }
        [Required(ErrorMessage = "El país es obligatorio")]
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        [Required(ErrorMessage = "El fecha de nacimiento es obligatoria")]
        public DateTime FechaNacimiento { get; set; }
        [Required(ErrorMessage = "El estado es obligatorio")]
        public bool Estado { get; set; }

    }
}

AplicationWebMVC/Controllers/CuentasController.cs
using AplicationWebMVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Storage;

namespace AplicationWebMVC.Controllers
{
    public class CuentasController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public CuentasController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Registro()
        {
            RegistroViewModel registroVM = new RegistroViewModel();
            return View(registroVM);
        }

        [HttpPost]
        public async Task<IActionResult> Registro(RegistroViewModel registroVM)
        {
            if (ModelState.IsValid)
            {
                var usuario = new AppUsuario()
                {
                    UserName = registroVM.Email,
                    Email = registroVM.Email,
                    Nombre = registroVM.Nombre,
                    Url = registroVM.Url,
                    CodigoPais = registroVM.CodigoPais,
                    Telefono = registroVM.Telefono,
                    Pais = registroVM.Pais,
                    Ciudad = registroVM.Ciudad,
                    Direccion = registroVM.Direccion,
                    FechaNacimiento = registroVM.FechaNacimiento,
                    Estado = registroVM.Estado

                };

                var resultado = await _userManager.CreateAsync(usuario,registroVM.Password);
                                
                if (resultado.Succeeded)
                {
                    await _signInManager.SignInAsync(usuario, false);

                    return RedirectToAction("Index", "Home");
                }
                ValidarErrores(resultado);
            }
            return View(registroVM);
        }

        [HttpGet]
        public async Task<IActionResult> Acceso()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Acceso(AccesoViewModel accesoVM)
        {
            if (ModelState.IsValid)
            {
                var resultado = await _signInManager.PasswordSignInAsync(accesoVM.Email,accesoVM.Password,accesoVM.RememberMe,false);
                if (resultado.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "Acceso inválido");
                    return View(accesoVM);
                }

            }
            return View(accesoVM);
        }



        private void ValidarErrores(IdentityResult resultado)
        {
            foreach (var error in resultado.Errors)
            {
                ModelState.AddModelError(String.Empty, error.Description);
            }
        }
    }
}

AplicationWebMVC/Controllers/HomeController.cs
using AplicationWebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AplicationWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AplicationWebMVC/Views/Cuentas/Acceso.cshtml
@model AccesoViewModel

@{
    ViewData["Title"] = "Acceso de usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title text-center">Acceso de cuentas</h3>
        <form asp-controller="Cuentas" asp-action="Acceso" method="post" role="form">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="row mt-4">
                <div class="col-sm-6">

                    <div class="mb-3">
                        <label asp-for="Email" class="col-md-2">Email:</label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Password" class="col-md-2">Contraseña:</label>
                        <input asp-for="Password" class="form-control" placeholder="Ingresa la contraseña" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <div class="custom-check">
                            <label asp-for="RememberMe" class="col-md-4">
                                <input asp-for="RememberMe" />
                                @Html.DisplayNameFor(m => m.RememberMe)
                            </label>
                        </div>
                    </div>

                </div>

                <div class="col-sm-4 offset-2">
                    <h3>Aquí acceso a aplicaciones externas</h3>
                </div>

            </div>

            

            <div class="row">
                <div class="col-sm-6 ">
                    <button type="submit" class="btn btn-success w-100 btn-lg">Acceder <i class="bi bi-box-arrow-in-right"></i></button>
                    <p><a asp-action="Registro">Registrarse como un nuevo usuario?</a></p>
                    <p><a asp-action="OlvidoPassword">Olvidaste tu contraseña ?</a></p>

                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
}

AplicationWebMVC/Views/Cuentas/Registro.cshtml
@model RegistroViewModel
@{
    ViewData["Title"] = "Registro de usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title text-center">Registro de cuentas</h3>
        <form asp-controller="Cuentas" asp-action="Registro" method="post" role="form">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="row mt-4">
                <div class="col-sm-6">
                    
                    <div class="mb-3">
                        <label asp-for="Nombre" class="col-md-2">Nombre:</label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre"/>
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Email" class="col-md-2">Email:</label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Url" class="col-md-2">Url:</label>
                        <input asp-for="Url" class="form-control" placeholder="Ingresa la url" />
                        <span asp-validation-for="Url" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="CodigoPais" class="col-md-3">Codigo país:</label>
                        <input asp-for="CodigoPais" class="form-control" placeholder="Ingresa el codigo teléfonico del país" />
                        <span asp-validation-for="CodigoPais" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Telefono" class="col-md-2">Teléfono:</label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el teléfono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Pais" class="col-md-2">País:</label>
                        <input asp-for="Pais" class="form-control" placeholder="Ingresa el país" />
                        <span asp-validation-for="Pais" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-sm-6">

                    <div class="mb-3">
                        <label asp-for="Ciudad" class="col-md-2">Ciudad:</label>
                        <input asp-for="Ciudad" class="form-control" placeholder="Ingresa la ciudad" />
                        <span asp-validation-for="Ciudad" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Direccion" class="col-md-2">Dirección:</label>
                        <input asp-for="Direccion" class="form-control" placeholder="Ingresa la dirección" />
                        <span asp-validation-for="Direccion" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="FechaNacimiento" class="col-md-4">Fecha de Nacimiento: <i class="bi bi-calendar-date"></i></label>
                        <input type="text" name="FechaNacimiento" class="form-control" id="datepicker" placeholder="Ejemplo: 1990-10-05" />
                        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Password" class="col-md-2">Contraseña:</label>
                        <input asp-for="Password" class="form-control" placeholder="Ingresa la contraseña" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ConfirmPassword" class="col-md-4">Confirmar contraseña:</label>
                        <input asp-for="ConfirmPassword" class="form-control" placeholder="Confirma la contraseña" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>

                </div>

            </div>
            <div class="row">
                <div class="col-sm-10 offset-2" >
                    <button type="submit" class="btn btn-success w-75 btn-lg">Registrarse</button>
                </div>
            </div>

        </form>
    </div>
</div>

@*<form asp-controller="Cuentas" asp-action="Registro" method="post" role="form">
    <div class="text-danger" asp-validation-summary="All"></div>
    
    <div class="form-group">
        <label asp-for="Nombre" class="col-md-2">Nombre</label>
        <div class="col-md-10">
            <input asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2">Email</label>
        <div class="col-md-10">
            <input asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Url" class="col-md-2">Url</label>
        <div class="col-md-10">
            <input asp-for="Url" class="form-control"/>
            <span asp-validation-for="Url" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="CodigoPais" class="col-md-2">Codigo del Pais</label>
        <div class="col-md-10">
            <input asp-for="CodigoPais" class="form-control" />
            <span asp-validation-for="CodigoPais" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Telefono" class="col-md-2">Telefono</label>
        <div class="col-md-10">
            <input asp-for="Telefono" class="form-control" />
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Pais" class="col-md-2">Pais</label>
        <div class="col-md-10">
            <input asp-for="Pais" class="form-control" />
            <span asp-validation-for="Pais" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Ciudad" class="col-md-2">Ciudad</label>
        <div class="col-md-10">
            <input asp-for="Ciudad" class="form-control" />
            <span asp-validation-for="Ciudad" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Direccion" class="col-md-2">Direccion</label>
        <div class="col-md-10">
            <input asp-for="Direccion" class="form-control" />
            <span asp-validation-for="Direccion" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="FechaNacimiento" class="col-md-2">Fecha Nacimiento</label>
        <div class="col-md-10">
            <input asp-for="FechaNacimiento" class="form-control" />
            <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2">Contraseña</label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2">Confirmar Contraseña</label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            <button type="submit" class="btn btn-success">Registrarse</button>
        </div>
    </div>

</form>*@

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
}

AplicationWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AplicationWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicationWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--Iconos de bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <!--Estilos jquery ui para datepicker-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicationWebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplicationWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Cuentas" asp-action="Registro">Registro</a>
                        </li>
                    </ul>

                    <!-- Vista parcial para acceso (login) y registro-->
                    <partial name="_LoginRegistroVistaParcial"></partial>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AplicationWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--Js para jquery de UI datepicker-->
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script >
        $(function(){
            $('#datepicker').datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: '1930:2020',
                dateFormat:'yy-mm-dd'
            })
        })
    </script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AplicationWebMVC/Views/Shared/_LoginRegistroVistaParcial.cshtml
<ul class="navbar-nav ml-auto"> 
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Cuentas" asp-action="Acceso">Acceder</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Cuentas" asp-action="Registro">Registro</a>
    </li>

</ul>